// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlwnevmqgfqhowpffqlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsd25ldm1xZ2ZxaG93cGZmcWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjc0ODgsImV4cCI6MjA2NzY0MzQ4OH0.zVbC-JL88KHTK_agDXOo68BaBrmoD8F8KYhqOUlqnD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});